name: VasaStrategies
favicon: null
layout_spectrum: 0.40338
typography_spectrum: 0.57902
title: Vasa Strategies
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#05baf3'
    - '#065aa3'
    - '#0080ff'
    - '#000080'
    - '#00ffff'
  brandStrength: 0.125
  lightness: 0.5625
  saturation: 0.875
  rhythmicContrast: 0.75
purpose: []
